#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

set -x

export GRADLE_VERSION=2.12
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-$GRADLE_VERSION
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/.gradle
export GRADLE_OPTS="-Xms384m -Xmx412m"

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$GRADLE_HOME/bin:$PATH


if [ ! -d $OPENSHIFT_DATA_DIR/gradle-$GRADLE_VERSION ]; then
		cd $OPENSHIFT_DATA_DIR
		wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
		unzip gradle-$GRADLE_VERSION-bin.zip
		rm -f gradle-$GRADLE_VERSION-bin.zip
fi


if [ ! -d $OPENSHIFT_DATA_DIR/.gradle ]; then
		mkdir $OPENSHIFT_DATA_DIR/.gradle
fi


cd $OPENSHIFT_REPO_DIR
gradle clean bootRepackage